inherit:
    - base.yaml

training:
    task: linear_regression  #
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    w_type: uniform
    learning_rate: 0.0005
out_dir: ../models12/w_uniform_linear  # 输出路径改变

wandb:
    name: "linear_regression_w_uniform" # log name 改变
