inherit:
    - base.yaml

training:
    task: linear_regression   # 仍然属于 linear  task 减少代码改动
    If_two_distribution: True
    If_RandomShuffle_2distribution: False
    train_steps: 1000001
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    learning_rate: 0.0003
    resume_id: 2distribution_lr
out_dir: ../models12/linear_regression_two_distribution  # 输出路径改变

wandb:
    name: "linear_regression_two_distribution" # wandb name 改变
